In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import plotly.express as px
from plotly.offline import init_notebook_mode
import re
import nltk
from nltk.corpus import stopwords
from tqdm import tqdm
from nltk.stem import WordNetLemmatizer
import spacy

nltk.download("omw-1.4", quiet=True)
nltk.download("stopwords", quiet=True)
nltk.download("wordnet", quiet=True)
tqdm.pandas()
spacy_eng = spacy.load("en_core_web_sm")
lem = WordNetLemmatizer()
init_notebook_mode(connected=True)
sns.set_style("darkgrid")
plt.rcParams["figure.figsize"] = (20,8)
plt.rcParams["font.size"] = 18

In [2]:
data = pd.read_csv('train.csv')
data.head(15)

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0
10,10,21,22,Method to find separation of slits using fresn...,What are some of the things technicians can te...,0
11,11,23,24,How do I read and find my YouTube comments?,How can I see all my Youtube comments?,1
12,12,25,26,What can make Physics easy to learn?,How can you make physics easy to learn?,1
13,13,27,28,What was your first sexual experience like?,What was your first sexual experience?,1
14,14,29,30,What are the laws to change your status from a...,What are the laws to change your status from a...,0

In [3]:
data.isnull().sum()

id              0
qid1            0
qid2            0
question1       1
question2       2
is_duplicate    0
dtype: int64

In [4]:
data.dropna(inplace=True)

In [5]:
fig = px.pie(data, values='id', names='is_duplicate', title='Duplicate And Non Duplicate Questions Percentage')
fig.show()

In [6]:
def text_cleaning(words):
    question = re.sub(r'\s+\n+', ' ', words)  # remove extra spaces and newlines
    question = re.sub(r'[^a-zA-Z0-9]', ' ', question)
    question = question.lower()
    return question

In [7]:
data['question1_clean'] = data['question1'].progress_apply(text_cleaning)
data['question2_clean'] = data['question2'].progress_apply(text_cleaning)
data

100%|██████████| 404287/404287 [00:01<00:00, 206951.04it/s]
100%|██████████| 404287/404287 [00:01<00:00, 220265.97it/s]

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0,what is the step by step guide to invest in sh...,what is the step by step guide to invest in sh...
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0,what is the story of kohinoor koh i noor dia...,what would happen if the indian government sto...
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0,how can i increase the speed of my internet co...,how can internet speed be increased by hacking...
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0,why am i mentally very lonely how can i solve...,find the remainder when math 23 24 math i...
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0,which one dissolve in water quikly sugar salt...,which fish would survive in salt water
...,...,...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0,how many keywords are there in the racket prog...,how many keywords are there in perl programmin...
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1,do you believe there is life after death,is it true that there is life after death
404287,404287,537928,537929,What is one coin?,What's this coin?,0,what is one coin,what s this coin
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0,what is the approx annual cost of living while...,i am having little hairfall problem but i want...
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0,what is like to have sex with cousin,what is it like to have sex with your cousin

In [8]:
data['question1_length'] = data['question1_clean'].apply(lambda x: len(x.split()))
data['question2_length'] = data['question2_clean'].apply(lambda x: len(x.split()))

In [9]:
px.histogram(data, x='question1_length', color='is_duplicate', title='Question 1 Length Distribution Plot')

In [10]:
px.histogram(data, x='question2_length', color='is_duplicate', title='Question 2 Length Distribution Plot')

In [11]:
questions1 = data['question1_clean'].tolist()
questions2 = data['question2_clean'].tolist()

In [12]:
wordcloud = WordCloud(max_words=1500, background_color='black').generate(" ".join(questions1))
plt.imshow(wordcloud, interpolation='bilinear')
plt.title('Words From Question1')
plt.axis('off')
plt.show()

In [13]:
wordcloud = WordCloud(max_words=1500, background_color='black').generate(" ".join(questions2))
plt.imshow(wordcloud, interpolation='bilinear')
plt.title('Words From Question2')
plt.axis('off')
plt.show()

In [14]:
data['question1_length'].describe()

count    404287.000000
mean         11.127968
std           5.571416
min           0.000000
25%           7.000000
50%          10.000000
75%          13.000000
max         128.000000
Name: question1_length, dtype: float64

In [15]:
data['question2_length'].describe()

count    404287.000000
mean         11.376792
std           6.480827
min           0.000000
25%           7.000000
50%          10.000000
75%          13.000000
max         248.000000
Name: question2_length, dtype: float64

In [16]:
import tensorflow as tf
import tf_keras
from tf_keras.preprocessing.text import Tokenizer
from tf_keras.preprocessing.sequence import pad_sequences
from tf_keras.utils import to_categorical
from tf_keras.models import Sequential, Model
from tf_keras import layers
from tf_keras.layers import (Embedding, Layer, Dense, Dropout, MultiHeadAttention,
                              LayerNormalization, Input, GlobalAveragePooling1D,
                              LSTM, Bidirectional)
from tf_keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from transformers import (AutoTokenizer, DataCollatorWithPadding, TFAutoModel,
                           DistilBertConfig, TFDistilBertModel, BertConfig,
                           TFBertModel, TFRobertaModel)
from datasets import load_dataset

WARNING:tensorflow:From c:\Users\Jay Singla\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [17]:
model_checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [18]:
def encode_text(text, tokenizer):
    encoded = tokenizer.batch_encode_plus(text, add_special_tokens=True, max_length=50,padding='max_length', truncation=True, return_attention_mask=True, return_tensors='tf')

    input_ids = np.array(encoded['input_ids'], dtype='int32')
    attention_masks = np.array(encoded['attention_mask'], dtype='int32')
    return {'input_ids': input_ids, 'attention_masks': attention_masks}

In [19]:
n_sample = min(400000, len(data))
data = data.sample(n_sample)
train = data.iloc[:int(n_sample * 0.80), :]
val = data.iloc[int(n_sample * 0.80):, :]

question1_train = encode_text(train["question1_clean"].tolist(), tokenizer)
question2_train = encode_text(train["question2_clean"].tolist(), tokenizer)
question1_val = encode_text(val["question1_clean"].tolist(), tokenizer)
question2_val = encode_text(val["question2_clean"].tolist(), tokenizer)

y_train = train["is_duplicate"].values
y_val = val["is_duplicate"].values

In [20]:
# Make data with 3 questions where 3rd question is entire random and not related to other questions

In [21]:
duplicate_data = data.query("is_duplicate == 1").copy()
duplicate_data

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean,question1_length,question2_length
281306,281306,98572,37324,What is the difference between AC and DC curr...,What is the difference between AC current and ...,1,what is the difference between ac and dc curr...,what is the difference between ac current and ...,9,10
247557,247557,29618,29028,What are the best laptops one can go for under...,What is the best laptop under the category of ...,1,what are the best laptops one can go for under...,what is the best laptop under the category of ...,14,11
367006,367006,179590,456245,Which one to buy? Honda hornet 160R or Suzuki ...,I am confused between Suzuki Gixxer SF FI and ...,1,which one to buy honda hornet 160r or suzuki ...,i am confused between suzuki gixxer sf fi and ...,10,26
148706,148706,234401,234402,Which is the best motor bike in the Royal Enfi...,Which is the best royal Enfield bike in 2016?,1,which is the best motor bike in the royal enfi...,which is the best royal enfield bike in 2016,11,9
145300,145300,229764,229765,What are the functional differences between ve...,What is the main difference between veins and ...,1,what are the functional differences between ve...,what is the main difference between veins and ...,9,9
...,...,...,...,...,...,...,...,...,...,...
280256,280256,399809,399810,What does Quora use to automatically update a ...,How does the Quora view counting system work?,1,what does quora use to automatically update a ...,how does the quora view counting system work,12,8
139664,139664,222129,222130,When you can't sleep at night what do you do?,"When you can not sleep at nights, what would y...",1,when you can t sleep at night what do you do,when you can not sleep at nights what would y...,11,11
294251,294251,92545,16340,"What is the Sahara, and how do the average tem...","What is the Sahara, and how do the average tem...",1,what is the sahara and how do the average tem...,what is the sahara and how do the average tem...,19,20
200142,200142,240469,34554,What was your initial reaction on getting to k...,What do you think about Modi Government decisi...,1,what was your initial reaction on getting to k...,what do you think about modi government decisi...,20,13
366291,366291,432213,304309,Do keywords and meta tags still important and ...,Is keyword ranking still important in SEO?,1,do keywords and meta tags still important and ...,is keyword ranking still important in seo,11,7

In [22]:
duplicate_data.shape

(147651, 10)

In [23]:
non_duplicate_data = data.query('is_duplicate == 0')
question3_col = list(non_duplicate_data[:duplicate_data.shape[0]]['question1'])
question3_col

['Why is Puerto Rico not a US state?',
 'How do I make myself mentally and emotionally strong?',
 'Does centrifugal force always acts or only in case of non inertial frame of reference?',
 'What should I do for being a WWE superstar?',
 'Is there real magic in the world?',
 'What is ordinary RC moment resisting frame?',
 'How do I recover deleted iCloud backup?',
 'How do I mirror my PC screen to a Samsung Smart TV wirelessly?',
 'Any engineering students or an engineer who can guide me the scope of mechatronics in abroad plzzz I really need your help?',
 'Art Conservation and Restoration: What are the conditions of replacing a bulb in a Dan Flavin piece?',
 'How do you fix an LG TV turning off all by itself?',
 'How do I understand the time value of money?',
 'Is this English sentence correct in grammar?',
 'Why does she treat me badly? And how can I over come it?',
 'Is it possible to be mentored by Jimmy Wales?',
 "What is Gabriel marcel's critiques on existentialism?",
 'What are some of the best economics books?',
 'Will Katrina Kaif marry Salman Khan?',
 'What is class struggle theory?',
 'How can I get an ISO certificate?',
 'What is the difference between an UberX, Uber Black and Uber Taxi?',
 'Both my parents are from Norway, but I learned English fluently when I was 5/6 years old. Am I bilingual?',
 'Why was the acronym SIPDE (scan, identify, predict, decide, execute) created?',
 "Why haven't Canada & Quebec parliaments updated the law to allow non-resident foreign work-from-home Canadian company employees to opt out of CPP/QPP?",
 'How do I fix Incredimail Socket Error 10041 Protocol wrong type for socket?',
 'What is a hash?',
 'What happens if you snort Tylenol PM?',
 'What are the possible pros and cons of the new decision of MHRD to remove weightage of class 12th marks in JEE Mains Rank from 2017 onwards?',
 'How do I read my spouses text msg?',
 'What are the strengths and weaknesses of Lúcio?',
 'How do I contact Nintendo for copyright to use their characters in Quiz?',
 'Aaas',
 "What are the subjects in which I can apply for my master's after completing my graduation in botany?",
 'I am 24 year jobless boy who graduated in IT but has done no good in life.how do I change and how can I get a job in IT industry to make a new start?',
 'What are some excellent facts about Chanda Kochhar?',
 'Where can I legally watch Dragon Ball Z episodes and movies?',
 'Being force to quit?',
 'Is it too late to learn to dance hip hop at 31 years old?',
 'I just started working with ERP Development but have interest in Java, Should I switch or there is enough growth in ERP Development?',
 'Can I use a Yongnuo - YN622N-TX (for Nikon) to trigger a YN622C-eTTL in manual mode only?',
 'What is the difference between an application software and an OS?',
 'Is masturbating good for health?',
 'How do carbon, oxygen and carbon dioxide atoms differ?',
 'How long does it take to film a stop motion movie like Kubo and the Two Strings?',
 'How do you get over fear of losing?',
 'How widely accepted are credit cards at small businesses and restaurants in Spain?',
 'What are adjectives used to describe winter?',
 "What are the main imports and exports of Venezuela, and how does Venezuela's industry compare to Suriname's?",
 'Who is the present HRD minister of India?',
 'Is this a German Shepherd dog?',
 'How do you make high resolution images?',
 'How do I turn off a screen overlay on my Samsung Galaxy s6?',
 'How do you describe a beautiful person?',
 'What are some synonyms for "looking forward to"?',
 'What all must I know as an electrical engineering student?',
 "What ideas were considered cutting edge science fiction in the 1930's but are now a reality?",
 'How does anal sex feel compared to vaginal sex?',
 'What would you do if you predict the future?',
 'What is the client master report (in equities)?',
 "What is feminists' attack?",
 'Why do men cum?',
 'What are the dirtiest cranial nerve mnemonics?',
 'Was all the indo pak war drama to buy new weapons from us russ Israel France?',
 'Do you love tarot reading?',
 'Why it is important for a student to be a learner as well?',
 'What is units digit exactly?',
 'What is the most important part of singing?',
 'What does "My love" mean?',
 'What are the largest corporate fines in history (by industry)?',
 'How was AC converted to DC before diodes were invented?',
 'Why is she so out of my league. I really like her but I dont know what to do. Help?',
 'What are the side courses that can be done with B.Com which should be useful and should be less costly…?',
 "I'm a Filipina VA who works for a racist US boss. What rights do I have?",
 'What are some examples of kinesics nonverbal communication?',
 'What is the value of a acceleration due to gravity?',
 'What should men know at age 30?',
 'Why is India not a member of NATO?',
 'What is Holden Commodore stud pattern and what are its advantages?',
 'What are some good astrologers in Bangalore?',
 'How do I get ripped in 3 months?',
 'Has Barack Obama been a good President overall?',
 "What's the salary for a Train Ticket Examiner (TTE) in Indian Railways?",
 'If I create a private list on Twitter, do the people in that list know they are on it?',
 "Why is it so that in Dubai one can't use Skype, Facetime and WhatsApp calling?",
 'What caused Sweden rape statistics to rise significantly in the past years?',
 'How do I make people aware of philanthropy concept?',
 'How can you learn faster and better?',
 "What are some superficial things in people's minds that would make them not vote for a qualified candidate to become POTUS?",
 'What are the best hotels in Dubai?',
 'What is space?',
 'Why is India itself divided into two parts: North India (under-developed) and South India (developing)?',
 'Is masturbating good while watching porn starting from the age of 14 (male) ? How many times should I masturbate in a week? Will it affect my studies?',
 'What are the ethical issues surrounding surrogate pregnancies?',
 'What are reviews for Code Geass?',
 'Is learning MATLAB necessary for civil engineers?',
 'Why do people in movies say "ah" before a sentence? Is it to make them look smarter?',
 'U.S. Congress: Why do we have both a Senate and House of Representatives?',
 'What are the therapeutic implications of a linear progression model vs. a parallel model in metastasis?',
 'I want to install CyanogenMod into my Energy system Neo 2 10.1" but I don\'t find how. Does somebody used to do it, or knows how?',
 'How does Bryant Eslava edit his photos?',
 'Should there be a war between India and Pakistan for Kashmir?',
 'What are some examples of things you can push and pull?',
 'What does the proposed corridor between Pakistan-China (between Pakistan’s southern Gwadar port on the Arabian Sea and China’s western Xinjiang region) mean for India?',
 "I have two years break up with the love of my life, can't move on am stuck and nt feeling to be in love am I okey?",
 "Why do some people don't like questions?",
 'What are some great flying machines?',
 'Did the USA government plan to commit acts of terrorism against its own people and blame it on Cuba?',
 'How do I forget someone whom I once loved deeply?',
 'What song do you have stuck in your head right now?',
 'Why do after every 28 years there is the same day?',
 'If you work at a luxury car dealership, what do you say if a teen comes in just to get a picture of himself, sitting in a car?',
 'I am doing graduation in management so, I wanted to know how much time will it take to complete CIMA after finishing my graduation?',
 'What does a hair transplant that lasts a lifetime cost?',
 'How do we see stars moving?',
 "The Time Traveler's Wife (2003 book): Why did Clare and Gomez express so little guilt and regret?",
 'Which DAW is easier to begin with FL studio vs Ableton Live? or even other DAWs',
 'Can you compare Bangalore days with Bangalore naatkal?',
 'Has the speed of light changed?',
 'Do I need a passport to go to Andaman islands?',
 'Which IC engine SI or CI has more specific output and why?',
 'What are the best sports league in the world and why are they the best?',
 'What individuals and events in history are a source of pride for Kazakhstan?',
 'How difficult is it get into RSI?',
 'What is 3D builder in windows 10?',
 'What song plays over the end credits to the 2002 movie Chance?',
 'How do I get a perfect 100 in economics class 12 cbse?',
 'How do I become a Muslim?',
 'What software is this?',
 'As a tester, how can I break a payment gateway?',
 'What is use of VPN?',
 'What companies are similar to IDEO in Brazil?',
 'What does cavalry mean?',
 'Is there any scope for an electronics engineering?',
 'What are your best memories in hostel?',
 'What deed in lieu of foreclosure means?',
 'Is Reliance JIO internet really unlimited?',
 'What is the difference between Lee-Enfield and Caracano?',
 'Do you want to get pregnant?',
 'How can I become a pilot in India that too a commercial pilot?',
 'What are some good mid-end-graphics games on PC?',
 "What's a good company for creating popup light boxes?",
 'When will be SSC CGL 2017 tier 1 exam?',
 'What are the requirements for starting up a Camping Agency/Company?',
 'What should I eat to get rid of belly fat?',
 'What is the procedure to locate the position of an element in the periodic table relating to its chemical reactivity?',
 'How long did it take you to get truly "buff" and sculpted muscles?',
 'How does the Dalai Lama compare to the Pope?',
 'Can someone tell if I am looking at their Instagram?',
 'What is difference between Hardware Engineer, Firmware Engineer & Embedded Engineer? Is it possible to switch from Hardware to Other two Engineering sections?',
 'How is Christianity different from Judaism?',
 'Is maths necessary in nda?',
 'Why does Quebec have its own star system and television shows? Why does it exist?',
 'What does the quote “God doesn’t play dice with the universe” by Albert Einstein mean?',
 'If I have someone blocked on Instagram, and view their story, can they see I viewed it?',
 'Can puppies get parvo from cats?',
 'How do you get super glue off metal?',
 'What is your motivation for life?',
 'What happens to unspent campaign contributions?',
 'How does one convert to Sikhism?',
 'What are the elements of brand strategy?',
 'Is there any trick to download Torrents with 0 seeds?',
 'What is the future of front end developer?',
 'Who is more important: the father or the mother?',
 'Which thing comes once in a year and twice in a month?',
 'What are the attributes of scientist by the name Sir Arthur Schuster?',
 'What do people ask most about surfing?',
 'What is the point of the United States Air Force when the US Navy can do the same job with its aircraft carriers?',
 'Where can I watch forevermore with English subtitles?',
 'Why do different biomes have different characteristic organisms?',
 'What is Mandelbrot Project (now known as LinkSmart) up to?',
 'What are the scams of revived youth cream?',
 'Should I get an electric guitar?',
 'What was invented in 2003?',
 "Does logging out of social media really helps in achieving one's goal?",
 'Who is the best character in Super Smash Bros Melee?',
 'Why are female doctors so beautiful?',
 'What the biggest mistake you have made?',
 'Where can I find  freight for Cargo Van?',
 'Are there any music similar to "Rain of brass petals" (version without vocals, composed by Akira Yamaoka)?',
 'What universities does NetSuite recruit new grads from? What majors are they looking for?',
 'How much will a trip to califonia cost?',
 'What are your thoughts about imaginary vs real time as Stephen Hawking describes?',
 'How often do Quora users anonymously ask/answer a questions and why?',
 'Can a psychopath fall in love?',
 'Which companies in India are recruiting mechanical engineering freshers?',
 'How do I screen cast in Android without using Chromecast?',
 'How to find Russian friends?',
 'What can I used as a middle name 4 genesis?',
 'What are the best book of thermodynamics for gate for different branches?',
 'How many sects in Islam? Why is there a disagreement on the number?',
 'Is it possible to install an open-source operating system on Blackberry Bold 9000? Which one?',
 'How would you measure the opportunity cost of military spending?',
 'What is electrical energy?',
 'Is there any practical way where we can earn money while staying in hostels and doing our MBA?',
 'What is your review of Io.js?',
 'How should I prepare green coffee?',
 'Why do the planets in our solar system circle the sun?',
 'What is the difference between the usage of 脸 and 面?',
 'I forgot my Facebook password and email password. How can I log into Facebook?',
 'What processor would give a better performance, a 2.7 GHz Dual-Core i5 or 2.2 GHz Dual-Core i7?',
 'What can Di-tert-butyl dicarbonate be used to do?',
 'My cousin likes me. What could I do to make him stop?',
 'What is the age of consent?',
 'What are some unexpected things first-time visitors to Tajikistan notice?',
 'How do you tell whether a fruit is sweet/ripe?',
 'Who are the current rising stars in linguistics?',
 'Do you have any creative and innovative ideas for a mobile app?',
 'What is the best way to approach students in online recruitment?',
 "I'm having a very difficult time getting back into the workforce after a failed business. Should I focus on reaching out to more people?",
 'Where is the best Samsung service center in Hyderabad?',
 'How can I turn $10,000 into $1,000,000 in one to five years?',
 'What is the English meaning of здравствуйте (zdravstvuyte)?',
 'How much of Made In Chelsea is fake?',
 'Is AlJazeera biased towards the Muslim and Arab community and biased against Israel?',
 "What are some good revenge porn websites? I don't watch revenge porn but I am doing a research paper on psychology behind revenge porn . Please help?",
 "Just found out the wife is pregnant, what are the do's and don'ts for a first time father?",
 "Events (leisure): What's the difference between a conference, a trade show, and a convention?",
 'What can an individual or a family or a business in Egypt do today to prepare and adapt for the coming impacts of climate change?',
 'What is the corporate culture like at Benchmark Electronics? How is the culture different than other companies?',
 'What does it feel like to use zolpidem (Ambien)?',
 'House numbers in one side of a street is odd and other side is even, how do we decide which side gets which?',
 'Do you think the Black Lives Matter movement is doing well without a political leader?',
 'Can you search Tinder without an account?',
 'How do you train a German Shepherd/Australian Shepherd mix?',
 'If the national language of the United States is not English, would the United Kingdom still have the influence that it has today?',
 'How accurate is radiation dating?',
 'Can worms see? If so, how?',
 'Is it normal to have a huge crush on a stranger whom you have never met in reality, but know a little bit about them through their social networking profile?',
 'Why do people perceive the USSR as less evil than Nazi Germany?',
 'How do I check my Western Union money order status?',
 'When will Amazon launch Echo in India?',
 'How can you start a pharmaceutical company?',
 'How are ENFPs introverted?',
 'What is the value of √556?',
 'Who are some lesser known important historical figures of Mongolia and what should people know about them?',
 'Which is the best shell case of Mac book Pro 15 inch retina?',
 "Why do British still bother about their queen? There's no contribution from them. Just burn away the country's resource.",
 'Is there anything better than LOTR and The Hobbit trilogies?',
 'What is the best way to make brownie?',
 'What are the best angel investors in Delhi NCR?',
 'Does any country allow someone to have 3 citizenships?',
 'How do you lose fat around your stomach?',
 'Which footballer has provided the most assists ever in footballing history?',
 'What are the trickiest questions asked in an interview?',
 'Where can I get level 2 CFA June 2016 scheweser books in pdf format?',
 'What is the difference between is and has?',
 'How much does a photographer for National Geographic get paid?',
 'Should I quit my PhD or what should I do?',
 'Natal Saturn in Pisces sign. Is this good or bad?',
 'What is the Christian case for sexual purity?',
 'What is the most shocking thing you’ve ever experienced?',
 'Ethical hacking certification for free?',
 'How much does a drive through coffee stand make in a year?',
 'What is a boobsize?',
 'How can we minimize the distance between two probability distributions?',
 'What college should I go to in Colorado?',
 'What are the best examples of social Entrepreneurship?',
 'What accomplishments has Halle Berry achieved?',
 'Whose the lyricist of a punjabi folk song “kala doriya” sung by Surinder Kaur and Parkash Kaur?',
 'What causes a pinky toe to turn sideways?',
 'Do you often like to sing?',
 'What makes shadows change?',
 'Why does sakura have a large forehead?',
 'I would like to do MS in aerospace engineering in USA.My GRE score is 306 Q:161 ,V:145.I have 7 CGPA in btech.what are the universities I can apply?',
 "What's the difference between device and internet IP addresses and how do they work together?",
 'Why do some aquatic mammals have dense fur while some have thick blubber instead?',
 'How can I get best results in my study & love relationship together?',
 "What does the Polish proverb 'not my circus, not my monkeys' mean?",
 'What percentage of users on Quora ask questions?',
 'Is it possible to do lateral entry in VIT?',
 'What is Brownstone Equation Editor 5 and what are its applications?',
 'What are the important facts about "X"?',
 "What are some tips on making it through the job interview process at Lowe's?",
 'What does the slang term "Becky" mean?',
 'How long does regular mail take to be delivered?',
 'How do you know if what you believe is right?',
 'How can I look at the mirror without a face?',
 'What are the main differences between Messi and Cristiano Ronaldo?',
 'Will Ravindra Babu provide helps afterwards GATE for clearing IIT/IISC interviews and written tests?',
 'How can I get valid 70-980 dumps?',
 'Is SABSA certification worth its value? Or should I go with more popular certs like CISSP and CISA etc?',
 'What skills take less than 5 minutes to learn that everyone should know how to do?',
 'Sinw wave in CAPL?',
 'What is the funniest thing you have ever heard?',
 'Where can I get online PDF or EPUB versions of books?',
 'Why is Reservation or Quota in any field necessary?',
 'What is the corporate culture like at Apache? How is the culture different than other companies?',
 'Who will win Super Bowl 51?',
 'How can I get account statements prior to April 2014 from State Bank of India? It’s not available online for the time before April 2014.',
 'Which are the similar websites like Postcrossing.com?',
 'Is it possible to play pirated games on PlayStation 4? If so, is there a way to do it without modifying the system?',
 'How much does a bus cost?',
 'In Interstellar, what does Cooper mean when he said that "Love, TARS. Love. My connection with Murph is quantifiable"?',
 'Succeeding with a babyface?',
 'How can I pass the 70-680 certification exam?',
 'How do you answer questions on Quora?',
 'Does the success of a self proclaimed Acharya Pankaj Pathak in Assam prove that we, as a state, are regressing back instead of progressing?',
 'How many times should a sales person insist on calling a client to make a sale?',
 "What does Adam D'Angelo think of Quora being addictive?",
 'How pancreatic cancer is treated?',
 'Does my female friend have feelings for me?',
 'How do you do a hard reset of a Kindle 3?',
 'Going for an IT job as a iOS developer in Canada from india. What should be the requirements?',
 'Would it be good if I graduate from Germany and Master from Stanford University (Please see details)?',

In [24]:
duplicate_data['question3'] = question3_col

In [25]:
duplicate_data.head(15)

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean,question1_length,question2_length,question3
281306,281306,98572,37324,What is the difference between AC and DC curr...,What is the difference between AC current and ...,1,what is the difference between ac and dc curr...,what is the difference between ac current and ...,9,10,Why is Puerto Rico not a US state?
247557,247557,29618,29028,What are the best laptops one can go for under...,What is the best laptop under the category of ...,1,what are the best laptops one can go for under...,what is the best laptop under the category of ...,14,11,How do I make myself mentally and emotionally ...
367006,367006,179590,456245,Which one to buy? Honda hornet 160R or Suzuki ...,I am confused between Suzuki Gixxer SF FI and ...,1,which one to buy honda hornet 160r or suzuki ...,i am confused between suzuki gixxer sf fi and ...,10,26,Does centrifugal force always acts or only in ...
148706,148706,234401,234402,Which is the best motor bike in the Royal Enfi...,Which is the best royal Enfield bike in 2016?,1,which is the best motor bike in the royal enfi...,which is the best royal enfield bike in 2016,11,9,What should I do for being a WWE superstar?
145300,145300,229764,229765,What are the functional differences between ve...,What is the main difference between veins and ...,1,what are the functional differences between ve...,what is the main difference between veins and ...,9,9,Is there real magic in the world?
19592,19592,37014,37015,Who is the most beautiful living actress?,Who is the most beautiful actress in the world?,1,who is the most beautiful living actress,who is the most beautiful actress in the world,7,9,What is ordinary RC moment resisting frame?
268993,268993,94774,331714,Since light is the fastest thing known in the ...,"If light can't escape a black hole, does this ...",1,since light is the fastest thing known in the ...,if light can t escape a black hole does this ...,33,22,How do I recover deleted iCloud backup?
20207,20207,38146,15970,How do I apply for pan card in bank?,How do I apply for PAN Card?,1,how do i apply for pan card in bank,how do i apply for pan card,9,7,How do I mirror my PC screen to a Samsung Smar...
341561,341561,180752,469419,What are the ill effects of porn?,What are the harmful effects of pornography?,1,what are the ill effects of porn,what are the harmful effects of pornography,7,7,Any engineering students or an engineer who ca...
352716,352716,481664,481665,How do I take a picture of myself?,What are some good ways to take a picture of m...,1,how do i take a picture of myself,what are some good ways to take a picture of m...,8,11,Art Conservation and Restoration: What are the...
271363,271363,71033,389432,How can we submit an HTML form without a submi...,How can you submit a form without a submit but...,1,how can we submit an html form without a submi...,how can you submit a form without a submit but...,11,13,How do you fix an LG TV turning off all by its...
172355,172355,266140,173490,Who will win the Barclays Premier League 2016-...,Who will win premier league this season 2016-2...,1,who will win the barclays premier league 2016 ...,who will win premier league this season 2016 2...,9,9,How do I understand the time value of money?
233589,233589,107511,58170,Has anyone got an interview invite for Google ...,Has anyone get interview call from Google afte...,1,has anyone got an interview invite for google ...,has anyone get interview call from google afte...,12,13,Is this English sentence correct in grammar?
253679,253679,265705,297705,What is the principle behind chromatography?,What is the basic principle of chromatography?,1,what is the principle behind chromatography,what is the basic principle of chromatography,6,7,Why does she treat me badly? And how can I ove...
193686,193686,96015,92412,How can I stop spending so much time on the In...,How do I ensure that I don't waste time on the...,1,how can i stop spending so much time on the in...,how do i ensure that i don t waste time on the...,11,13,Is it possible to be mentored by Jimmy Wales?

In [26]:
duplicate_data['question3_clean'] = duplicate_data['question3'].progress_apply(text_cleaning)

100%|██████████| 147651/147651 [00:00<00:00, 206318.41it/s]

In [27]:
duplicate_data.head(25)

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean,question1_length,question2_length,question3,question3_clean
281306,281306,98572,37324,What is the difference between AC and DC curr...,What is the difference between AC current and ...,1,what is the difference between ac and dc curr...,what is the difference between ac current and ...,9,10,Why is Puerto Rico not a US state?,why is puerto rico not a us state
247557,247557,29618,29028,What are the best laptops one can go for under...,What is the best laptop under the category of ...,1,what are the best laptops one can go for under...,what is the best laptop under the category of ...,14,11,How do I make myself mentally and emotionally ...,how do i make myself mentally and emotionally ...
367006,367006,179590,456245,Which one to buy? Honda hornet 160R or Suzuki ...,I am confused between Suzuki Gixxer SF FI and ...,1,which one to buy honda hornet 160r or suzuki ...,i am confused between suzuki gixxer sf fi and ...,10,26,Does centrifugal force always acts or only in ...,does centrifugal force always acts or only in ...
148706,148706,234401,234402,Which is the best motor bike in the Royal Enfi...,Which is the best royal Enfield bike in 2016?,1,which is the best motor bike in the royal enfi...,which is the best royal enfield bike in 2016,11,9,What should I do for being a WWE superstar?,what should i do for being a wwe superstar
145300,145300,229764,229765,What are the functional differences between ve...,What is the main difference between veins and ...,1,what are the functional differences between ve...,what is the main difference between veins and ...,9,9,Is there real magic in the world?,is there real magic in the world
19592,19592,37014,37015,Who is the most beautiful living actress?,Who is the most beautiful actress in the world?,1,who is the most beautiful living actress,who is the most beautiful actress in the world,7,9,What is ordinary RC moment resisting frame?,what is ordinary rc moment resisting frame
268993,268993,94774,331714,Since light is the fastest thing known in the ...,"If light can't escape a black hole, does this ...",1,since light is the fastest thing known in the ...,if light can t escape a black hole does this ...,33,22,How do I recover deleted iCloud backup?,how do i recover deleted icloud backup
20207,20207,38146,15970,How do I apply for pan card in bank?,How do I apply for PAN Card?,1,how do i apply for pan card in bank,how do i apply for pan card,9,7,How do I mirror my PC screen to a Samsung Smar...,how do i mirror my pc screen to a samsung smar...
341561,341561,180752,469419,What are the ill effects of porn?,What are the harmful effects of pornography?,1,what are the ill effects of porn,what are the harmful effects of pornography,7,7,Any engineering students or an engineer who ca...,any engineering students or an engineer who ca...
352716,352716,481664,481665,How do I take a picture of myself?,What are some good ways to take a picture of m...,1,how do i take a picture of myself,what are some good ways to take a picture of m...,8,11,Art Conservation and Restoration: What are the...,art conservation and restoration what are the...
271363,271363,71033,389432,How can we submit an HTML form without a submi...,How can you submit a form without a submit but...,1,how can we submit an html form without a submi...,how can you submit a form without a submit but...,11,13,How do you fix an LG TV turning off all by its...,how do you fix an lg tv turning off all by its...
172355,172355,266140,173490,Who will win the Barclays Premier League 2016-...,Who will win premier league this season 2016-2...,1,who will win the barclays premier league 2016 ...,who will win premier league this season 2016 2...,9,9,How do I understand the time value of money?,how do i understand the time value of money
233589,233589,107511,58170,Has anyone got an interview invite for Google ...,Has anyone get interview call from Google afte...,1,has anyone got an interview invite for google ...,has anyone get interview call from google afte...,12,13,Is this English sentence correct in grammar?,is this english sentence correct in grammar
253679,253679,265705,297705,What is the principle behind chromatography?,What is the basic principle of chromatography?,1,what is the principle behind chromatography,what is the basic principle of chromatography,6,7,Why does she treat me badly? And how can I ove...,why does she treat me badly and how can i ove...
193686,193686,96015,92412,How can I stop spending so much time on the In...,How do I ensure that I don't waste time on the...,1,how can i stop spending so much time on the in...,how do i ensure that i don t waste time on the...,11,13,Is it possible to be mentored by Jimmy Wales?,is it possible to be mentored by jimmy wales
331951,331951,136946,154964,"If somebody has a good startup idea, then how ...",How should I convince a startup investor that ...,1,if somebody has a good startup idea then how ...,how should i convince a startup investor that ...,19,14,What is Gabriel marcel's critiques on existent...,what is gabriel marcel s critiques on existent...
30986,30986,57159,57160,How can I become a good photographer?,What are the basic tips to become a good photo...,1,how can i become a good photographer,what are the basic tips to become a good photo...,7,10,What are some of the best economics books?,what are some of the best economics books
250489,250489,364385,351745,Gnosticism: Why does the Roman Catholic Bible ...,Why are there more books in the Catholic bible...,1,gnosticism why does the roman catholic bible ...,why are there more books in the catholic bible...,17,13,Will Katrina Kaif marry Salman Khan?,will katrina kaif marry salman khan
189249,189249,4018,11343,How would demonetizing 500 and 1000 rupee note...,How can black money brought out by discontinui...,1,how would demonetizing 500 and 1000 rupee note...,how can black money brought out by discontinui...,20,12,What is class struggle theory?,what is class struggle theory
106425,106425,50579,78236,Is CAT after b.tech in mechanical engineering ...,I'm a mechanical engineering student. What ski...,1,is cat after b tech in mechanical engineering ...,i m a mechanical engineering student what ski...,9,16,How can I get an ISO certificate?,how can i get an iso certificate
278856,278856,110414,181856,What is the best earphones under rs 500 in india?,Which is the best earphone under rs500?,1,what is the best earphones under rs 500 in india,which is the best earphone under rs500,10,7,"What is the difference between an UberX, Uber ...",what is the difference between an uberx uber ...
141584,141584,167053,224730,What should I blog about?,How do I discover what I should write my blog ...,1,what should i blog about,how do i discover what i should write my blog ...,5,11,"Both my parents are from Norway, but I learned...",both my parents are from norway but i learned...
234146,234146,344574,344575,Do you need to be good in school to become an ...,Do you need to be good in school in order to b...,1,do you need to be good in school to become an ...,do you need to be good in school in order to b...,12,14,"Why was the acronym SIPDE (scan, identify, pre...",why was the acronym sipde scan identify pre...
311297,311297,435553,197974,Why dont Indian Muslims join Indian army?,Why do very few Muslims seem to join the India...,1,why dont indian muslims join indian army,why do very few muslims seem to join the india...,7,11,Why haven't Canada & Quebec parliaments update...,why haven t canada quebec parliaments update...
396442,396442,529503,441166,Atheists: What caused you to become atheists?,How and why did you become an atheist?,1,atheists what caused you to become atheists,how and why did you become an atheist,7,8,How do I fix Incredimail Socket Error 10041 Pr...,how do i fix incredimail socket error 10041 pr...

In [28]:
train = duplicate_data.iloc[:int(duplicate_data.shape[0]*0.80),:]
val = duplicate_data.iloc[int(duplicate_data.shape[0]*0.80):,:]

question1_train = encode_text(train['question1_clean'].tolist(), tokenizer)
question2_train = encode_text(train['question2_clean'].tolist(), tokenizer)
question3_train = encode_text(train['question3_clean'].tolist(), tokenizer)

question1_val = encode_text(val['question1_clean'].tolist(), tokenizer)
question2_val = encode_text(val['question2_clean'].tolist(), tokenizer)
question3_val = encode_text(val['question3_clean'].tolist(), tokenizer)

In [29]:
class DistanceLayer(Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, anchor, positive, negative):
        positive_distance = tf.reduce_sum(tf.square(anchor - positive), -1)
        negative_distance = tf.reduce_sum(tf.square(anchor - negative), -1)
        return positive_distance, negative_distance

In [30]:
from tf_keras import metrics

In [31]:
class SiameseModel(Model):

    def __init__(self, siamese_network, margin=0.5):
        super(SiameseModel, self).__init__()
        self.siamese_network = siamese_network
        self.margin = margin
        self.loss_tracker = metrics.Mean(name="loss")

    def call(self, inputs):
        return self.siamese_network(inputs)

    def train_step(self, data):

        with tf.GradientTape() as tape:
            loss = self._compute_loss(data)

        gradients = tape.gradient(loss, self.siamese_network.trainable_weights)
        self.optimizer.apply_gradients(
            zip(gradients, self.siamese_network.trainable_weights)
        )
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    def test_step(self, data):
        loss = self._compute_loss(data)
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    def _compute_loss(self, data):
        ap_distance, an_distance = self.siamese_network(data)
        loss = ap_distance - an_distance
        loss = tf.maximum(loss + self.margin, 0.0)
        return loss

    @property
    def metrics(self):
        return [self.loss_tracker]

In [32]:
transformer_model = TFBertModel.from_pretrained(model_checkpoint)

input_ids_in1   = Input(shape=(50,), name='input_ids1',     dtype='int32')
input_masks_in1 = Input(shape=(50,), name='attention_mask1', dtype='int32')

anchor_input   = Input(name='anchor_ids',    shape=(50,), dtype='int32')
anchor_masks   = Input(name='anchor_mask',   shape=(50,), dtype='int32')
positive_input = Input(name='positive_ids',  shape=(50,), dtype='int32')
positive_masks = Input(name='positive_mask', shape=(50,), dtype='int32')
negative_input = Input(name='negative_ids',  shape=(50,), dtype='int32')
negative_masks = Input(name='negative_mask', shape=(50,), dtype='int32')

embedding_layer = transformer_model(input_ids_in1, attention_mask=input_masks_in1).last_hidden_state

average = GlobalAveragePooling1D()(embedding_layer)
embeds  = Dense(512, activation='relu')(average)
embeddings = Model(inputs=[input_ids_in1, input_masks_in1], outputs=embeds)

for layer in embeddings.layers[:-1]:
    layer.trainable = False

embeds1 = embeddings([anchor_input,   anchor_masks])
embeds2 = embeddings([positive_input, positive_masks])
embeds3 = embeddings([negative_input, negative_masks])

distances = DistanceLayer()(embeds1, embeds2, embeds3)

siamese_network = Model(
    inputs=[anchor_input, anchor_masks, positive_input, positive_masks,
            negative_input, negative_masks],
    outputs=distances
)

siamese_model = SiameseModel(siamese_network)
siamese_model.compile(optimizer=tf_keras.optimizers.Adam(0.00001))

# tf.data.Dataset ensures Keras batches along axis-0 (not len(tuple)=6)
BATCH_SIZE = 32

train_dataset = tf.data.Dataset.from_tensor_slices((
    np.asarray(question1_train['input_ids']),
    np.asarray(question1_train['attention_masks']),
    np.asarray(question2_train['input_ids']),
    np.asarray(question2_train['attention_masks']),
    np.asarray(question3_train['input_ids']),
    np.asarray(question3_train['attention_masks'])
)).batch(BATCH_SIZE)

val_dataset = tf.data.Dataset.from_tensor_slices((
    np.asarray(question1_val['input_ids']),
    np.asarray(question1_val['attention_masks']),
    np.asarray(question2_val['input_ids']),
    np.asarray(question2_val['attention_masks']),
    np.asarray(question3_val['input_ids']),
    np.asarray(question3_val['attention_masks'])
)).batch(BATCH_SIZE)

history = siamese_model.fit(
    train_dataset,
    epochs=10,
    validation_data=val_dataset
)

In [ ]:
plt.figure(figsize=(20,8))
plt.plot(history.history["loss"])
if "val_loss" in history.history:
    plt.plot(history.history["val_loss"])
    plt.legend(["train", "val"], loc="upper left")
else:
    plt.legend(["train"], loc="upper left")
plt.title("model loss")
plt.ylabel("loss")
plt.xlabel("epoch")
plt.show()

In [ ]:
def get_cosine_similarity(sentence1, sentence2):
    f1 = text_cleaning(sentence1)
    f1 = encode_text([f1], tokenizer)
    f2 = text_cleaning(sentence2)
    f2 = encode_text([f2], tokenizer)

    f1_inputs = np.array(f1['input_ids'])
    f1_masks = np.array(f1['attention_masks'])
    f2_inputs = np.array(f2['input_ids'])
    f2_masks = np.array(f2['attention_masks'])

    embeddings1 = embeddings([f1_inputs, f1_masks])
    embeddings2 = embeddings([f2_inputs, f2_masks])

    cosine_similarity = metrics.CosineSimilarity()
    return cosine_similarity(embeddings1, embeddings2).numpy()

In [ ]:
sentence1 = 'Is Earth circle in shape ?'
sentence2 = 'Should I learn python as it is very popular ?'
get_cosine_similarity(sentence1,sentence2)

In [ ]:
sentence1 = 'Python is one of the most popular programming language out there'
sentence2 = 'Should I learn python programming as it is very popular ?'
get_cosine_similarity(sentence1,sentence2)

In [ ]:
sentence1 = 'Which GPU gives a better performance NVIDIA or AMD ?'
sentence2 = 'My friend has a NVIDIA GPU, and he suggests that it gives a very smooth gaming performance'
get_cosine_similarity(sentence1,sentence2)